//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 07:29:15 PM EEST 
//


package fi.csc.orcidconnect.push.soap.schema.cscidmtest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}association"/&gt;
 *         &lt;element ref="{}modify-attr"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="class-name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "association",
    "modifyAttr"
})
@XmlRootElement(name = "modify")
public class Modify {

    @XmlElement(required = true)
    protected Association association;
    @XmlElement(name = "modify-attr", required = true)
    protected ModifyAttr modifyAttr;
    @XmlAttribute(name = "class-name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String className;

    /**
     * Gets the value of the association property.
     * 
     * @return
     *     possible object is
     *     {@link Association }
     *     
     */
    public Association getAssociation() {
        return association;
    }

    /**
     * Sets the value of the association property.
     * 
     * @param value
     *     allowed object is
     *     {@link Association }
     *     
     */
    public void setAssociation(Association value) {
        this.association = value;
    }

    /**
     * Gets the value of the modifyAttr property.
     * 
     * @return
     *     possible object is
     *     {@link ModifyAttr }
     *     
     */
    public ModifyAttr getModifyAttr() {
        return modifyAttr;
    }

    /**
     * Sets the value of the modifyAttr property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModifyAttr }
     *     
     */
    public void setModifyAttr(ModifyAttr value) {
        this.modifyAttr = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

}
