//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 06:40:42 PM EEST 
//


package fi.csc.orcidconnect.push.soap.schema.cscidmtest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}remove-all-values"/&gt;
 *         &lt;element ref="{}add-value"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="attr-name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "removeAllValues",
    "addValue"
})
@XmlRootElement(name = "modify-attr")
public class ModifyAttr {

    @XmlElement(name = "remove-all-values", required = true)
    protected RemoveAllValues removeAllValues;
    @XmlElement(name = "add-value", required = true)
    protected AddValue addValue;
    @XmlAttribute(name = "attr-name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String attrName;

    /**
     * Gets the value of the removeAllValues property.
     * 
     * @return
     *     possible object is
     *     {@link RemoveAllValues }
     *     
     */
    public RemoveAllValues getRemoveAllValues() {
        return removeAllValues;
    }

    /**
     * Sets the value of the removeAllValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemoveAllValues }
     *     
     */
    public void setRemoveAllValues(RemoveAllValues value) {
        this.removeAllValues = value;
    }

    /**
     * Gets the value of the addValue property.
     * 
     * @return
     *     possible object is
     *     {@link AddValue }
     *     
     */
    public AddValue getAddValue() {
        return addValue;
    }

    /**
     * Sets the value of the addValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddValue }
     *     
     */
    public void setAddValue(AddValue value) {
        this.addValue = value;
    }

    /**
     * Gets the value of the attrName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * Sets the value of the attrName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttrName(String value) {
        this.attrName = value;
    }

}
