---
server:
  contextPath: '/app'
  session:
    # to avoid castexceptions on startup
    persistent: false
spring:
  mvc:
    favicon:
      enabled: false

my:
  oauth2client:
    # define authentication providers in use
    providerList: 'google,git,orcidSandbox'
    defaultProvider: 'orcidSandbox'
    specialCase: 'orcidSandbox'
    callBackBase: 'https://orcid-connect01.csc.fi:4443/app/'
#    callBackBase: http://localhost:8080/app/
  pushInterfaces:
    - uniarts
    - hakaTest
  pushInterfaceSpecs:
    uniarts:
      idp: 'https://idp.testshib.org/idp/shibboleth'
      relayerImplClass: 'fi.csc.orcidconnect.push.rest.RestJsonClient.java'
      restUrl: 'https://demo9650738.mockable.io/identities'
      authUser: 'user'
      authPass: 'pass'
    hakaTest:
      idp: 'https://testidp.funet.fi/idp/shibboleth'
      relayerImplClass: 'fi.csc.orcidconnect.push.soac.MockSoapClient.java'
      schemaPackage: 'fi.csc.orcidconnect.push.soap.schema.csc'
      soapUrl: 'https://demo9650738.mockable.io/mockProvisioningBinding'
      soapAction: 'http://www.novell.com/provisioning/service/receive'
    

# Be aware with leading white space on resource
# variables. They will cause extra characters
# on oauth ids and authentication will fail

# Google OAuth2 settings
google:
  clientId: '${clientId}'
  clientSecret: '${clientSecret}'
  tokenUriStr: 'https://accounts.google.com/o/oauth2/token'
  authUriStr: 'https://accounts.google.com/o/oauth2/auth'
  scope: 'profile'
  userInfoUri: 'https://www.googleapis.com/userinfo/v2/me'

# Git OAuth2 settings
git:
  clientId: '${gitClientId}'
  clientSecret: '${gitClientSecret}'
  tokenUriStr: 'https://github.com/login/oauth/access_token'
  authUriStr: 'https://github.com/login/oauth/authorize'
  # only read access when scope is not defined
  scope: 'user'
  userInfoUri: 'https://api.github.com/user'

orcidSandbox:
  clientId: '${orcidSandboxClientId}'
  clientSecret: '${orcidSandboxClientSecret}'
  tokenUriStr: 'https://api.sandbox.orcid.org/oauth/token'
  authUriStr: 'http://sandbox.orcid.org/oauth/authorize'
  scope: '/authenticate'
  userInfoUri: 'https://api.sandbox.orcid.org/orcid_id'
