//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 09:50:14 AM EET 
//


package fi.csc.orcidconnect.push.soap.schema.identitiesdescriptor;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element ref="{https://confluence.csc.fi/x/d4p5Aw}Name"/&gt;
 *         &lt;element ref="{https://confluence.csc.fi/x/d4p5Aw}NameFormat" minOccurs="0"/&gt;
 *         &lt;element ref="{https://confluence.csc.fi/x/d4p5Aw}FriendlyName" minOccurs="0"/&gt;
 *         &lt;element ref="{https://confluence.csc.fi/x/d4p5Aw}Issuer" minOccurs="0"/&gt;
 *         &lt;element ref="{https://confluence.csc.fi/x/d4p5Aw}IssueInstant" minOccurs="0"/&gt;
 *         &lt;element ref="{https://confluence.csc.fi/x/d4p5Aw}Mediator" minOccurs="0"/&gt;
 *         &lt;element ref="{https://confluence.csc.fi/x/d4p5Aw}MediationInstant" minOccurs="0"/&gt;
 *         &lt;element ref="{https://confluence.csc.fi/x/d4p5Aw}IdentifierValue"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Identifier")
public class Identifier {
	
	public final static String EPPNFRNAME = "eduPersonPrincipalName";
//	public final static String EPPNOID = "urn:oid:1.3.6.1.4.1.5923.1.1.1.6";
	public final static String ORCIDFRNAME = "eduPersonOrcid";
//	public final static String ORCIDOID = "urn:oid:1.3.6.1.4.1.5923.1.1.1.16";
//	public final static String ATTRNAMEFORMAT = "urn:oasis:names:tc:SAML:2.0:attrname-format:uri";

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "NameFormat")
    @XmlSchemaType(name = "anyURI")
    protected String nameFormat;
    @XmlElement(name = "FriendlyName")
    protected String friendlyName;
    @XmlElement(name = "Issuer")
    @XmlSchemaType(name = "anyURI")
    protected String issuer;
    @XmlElement(name = "IssueInstant")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar issueInstant;
    @XmlElement(name = "Mediator")
    @XmlSchemaType(name = "anyURI")
    protected String mediator;
    @XmlElement(name = "MediationInstant")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar mediationInstant;
    @XmlElement(name = "IdentifierValue", required = true)
    protected String identifierValue;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the nameFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameFormat() {
        return nameFormat;
    }

    /**
     * Sets the value of the nameFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameFormat(String value) {
        this.nameFormat = value;
    }

    /**
     * Gets the value of the friendlyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFriendlyName() {
        return friendlyName;
    }

    /**
     * Sets the value of the friendlyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFriendlyName(String value) {
        this.friendlyName = value;
    }

    /**
     * Gets the value of the issuer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuer() {
        return issuer;
    }

    /**
     * Sets the value of the issuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuer(String value) {
        this.issuer = value;
    }

    /**
     * Gets the value of the issueInstant property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIssueInstant() {
        return issueInstant;
    }

    /**
     * Sets the value of the issueInstant property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIssueInstant(XMLGregorianCalendar value) {
        this.issueInstant = value;
    }

    /**
     * Gets the value of the mediator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediator() {
        return mediator;
    }

    /**
     * Sets the value of the mediator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediator(String value) {
        this.mediator = value;
    }

    /**
     * Gets the value of the mediationInstant property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMediationInstant() {
        return mediationInstant;
    }

    /**
     * Sets the value of the mediationInstant property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMediationInstant(XMLGregorianCalendar value) {
        this.mediationInstant = value;
    }

    /**
     * Gets the value of the identifierValue property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public String getIdentifierValue() {
        return identifierValue;
    }

    /**
     * Sets the value of the identifierValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIdentifierValue(String value) {
        this.identifierValue = value;
    }

}
