//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 09:50:14 AM EET 
//


package fi.csc.orcidconnect.push.soap.schema.identitiesdescriptor;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fi.csc.orcidconnect.push.soap.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Name_QNAME = new QName("https://confluence.csc.fi/x/d4p5Aw", "Name");
    private final static QName _NameFormat_QNAME = new QName("https://confluence.csc.fi/x/d4p5Aw", "NameFormat");
    private final static QName _FriendlyName_QNAME = new QName("https://confluence.csc.fi/x/d4p5Aw", "FriendlyName");
    private final static QName _Issuer_QNAME = new QName("https://confluence.csc.fi/x/d4p5Aw", "Issuer");
    private final static QName _IssueInstant_QNAME = new QName("https://confluence.csc.fi/x/d4p5Aw", "IssueInstant");
    private final static QName _Mediator_QNAME = new QName("https://confluence.csc.fi/x/d4p5Aw", "Mediator");
    private final static QName _MediationInstant_QNAME = new QName("https://confluence.csc.fi/x/d4p5Aw", "MediationInstant");
    private final static QName _IdentifierValue_QNAME = new QName("https://confluence.csc.fi/x/d4p5Aw", "IdentifierValue");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fi.csc.orcidconnect.push.soap.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IdentitiesDescriptor }
     * 
     */
    public IdentitiesDescriptor createIdentitiesDescriptor() {
        return new IdentitiesDescriptor();
    }

    /**
     * Create an instance of {@link IdentityDescriptor }
     * 
     */
    public IdentityDescriptor createIdentityDescriptor() {
        return new IdentityDescriptor();
    }

    /**
     * Create an instance of {@link Identifier }
     * 
     */
    public Identifier createIdentifier() {
        return new Identifier();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://confluence.csc.fi/x/d4p5Aw", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://confluence.csc.fi/x/d4p5Aw", name = "NameFormat")
    public JAXBElement<String> createNameFormat(String value) {
        return new JAXBElement<String>(_NameFormat_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://confluence.csc.fi/x/d4p5Aw", name = "FriendlyName")
    public JAXBElement<String> createFriendlyName(String value) {
        return new JAXBElement<String>(_FriendlyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://confluence.csc.fi/x/d4p5Aw", name = "Issuer")
    public JAXBElement<String> createIssuer(String value) {
        return new JAXBElement<String>(_Issuer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://confluence.csc.fi/x/d4p5Aw", name = "IssueInstant")
    public JAXBElement<XMLGregorianCalendar> createIssueInstant(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_IssueInstant_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://confluence.csc.fi/x/d4p5Aw", name = "Mediator")
    public JAXBElement<String> createMediator(String value) {
        return new JAXBElement<String>(_Mediator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://confluence.csc.fi/x/d4p5Aw", name = "MediationInstant")
    public JAXBElement<XMLGregorianCalendar> createMediationInstant(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_MediationInstant_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://confluence.csc.fi/x/d4p5Aw", name = "IdentifierValue")
    public JAXBElement<Object> createIdentifierValue(Object value) {
        return new JAXBElement<Object>(_IdentifierValue_QNAME, Object.class, null, value);
    }

}
