//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.06 at 12:33:47 AM EET 
//


package fi.csc.orcidconnect.push.soap.schema.csc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fi.csc.orcidconnect.push.soap.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AddCommentRequestArg0_QNAME = new QName("http://www.novell.com/provisioning/service", "arg0");
    private final static QName _AddCommentRequestArg1_QNAME = new QName("http://www.novell.com/provisioning/service", "arg1");
  
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fi.csc.orcidconnect.push.soap.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReceiveRequest }
     * 
     */
    public ReceiveRequest createReceiveRequest() {
        return new ReceiveRequest();
    }

    /**
     * Create an instance of {@link ReceiveResponse }
     * 
     */
    public ReceiveResponse createReceiveResponse() {
        return new ReceiveResponse();
    }

 
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.novell.com/provisioning/service", name = "arg0", scope = ReceiveRequest.class)
    public JAXBElement<String> createReceiveRequestArg0(String value) {
        return new JAXBElement<String>(_AddCommentRequestArg0_QNAME, String.class, ReceiveRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.novell.com/provisioning/service", name = "arg1", scope = ReceiveRequest.class)
    public JAXBElement<String> createReceiveRequestArg1(String value) {
        return new JAXBElement<String>(_AddCommentRequestArg1_QNAME, String.class, ReceiveRequest.class, value);
    }

}
